namespace NodeScope.Desktop.Tests.Fakes;

/// <summary>
/// Tiny official xBIM test models used to exercise real versioned wire data.
/// CubeA is wexBIM v4; TwoProxy is v1 and contains two transformed instances.
/// Source: xBimTeam/XbimWebUI tests/data.
/// </summary>
internal static class WexBimFixture
{
    public static byte[] CubeA() => Convert.FromBase64String(
        "lVecBQQBAAAACAAAAAwAAAAAAAAAAQAAAAUAAAAAAHpEnBKOCYMhxsEbEHToQgzPwQAAAAAAAGnAAQABAAAACGAGRAhgBkQAAPpDAAAAAAAAAAAAAAAACGCGRAhghkQAAHpElAAAAP/+/j7//v4+//7+PgAAgD+UAAAA//7+Pv/+/j7//v4+AACAP5QAAAD//v4+//7+Pv/+/j4AAIA/lAAAAP/+/j7//v4+//7+PgAAgD+UAAAA//7+Pv/+/j7//v4+AACAP8EAAAAwAgAAAAAAAAAAAAAAAAhghkQIYIZEAAB6RAEAAAABAAAAwQAAADACAAAAAJQAAAC1AAAAAQgAAAAMAAAAwOYLs8I8eUQAAAAAehqcQuDmC7MAAHpEwOYLs8I8eUQAAHpEehqcQuDmC7MAAAAACGCGRHoanEIAAHpECGCGRHoanEIAAAAAwjx5RAhghkQAAAAAwjx5RAhghkQAAHpEBgAAAAIAAADBhAABAgEAAwIAAAA/9QMEAQQDBQIAAAA/dwQGBwYEBQIAAADCBgcAAgAHBgIAAAB+fgYDAAMGBQIAAAAAfgEHAgcBBA==");

    public static byte[] TwoProxy() => Convert.FromBase64String(
        "lVecBQEBAAAACAAAABgAAAACAAAAAgAAAAEAAAAAAHpEAQABAAAAbRevxNL2k0QAgLtESA1sxaTtKkQAAAAAkYGURQAAekQAgDtF0P3//zMzcz/Xo3A/pHA9PwAAgD+UAAAAMAJIDWzFpO0qRAAAAAAAAHpEAAB6RACAO0WyAAAAMALREsXBpO0qRAAAAAAAAHpEAAB6RACAO0UCAAAAsgAAADACAQAAAND9//8AAIA/AAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAACAPwAAAADREsXBpO0qRAAAAAAAAIA/lAAAADACAgAAAND9//8AAIA/AAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAACAPwAAAABIDWzFpO0qRAAAAAAAAIA/AQgAAAAMAAAAAAB6RAAAekQAAAAAAAB6RAAAekQAgDtFAAAAAAAAekQAAAAAAAAAAAAAekQAgDtFAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDtFAAB6RAAAAAAAAAAAAAB6RAAAAAAAgDtFBgAAAAIAAAC9vQEAAgMBAgIAAAD8vQMCBAUDBAIAAAA/vQUEBgcFBgIAAAB+vQcGAAEHAAIAAAB+AAYCAAYEAgIAAAB+fgEDBwMFBw==");
}
