#!/usr/bin/env node
/*
 * ifc-worker-harness/main.cjs — Electron entry for the IFC Web Worker live-runtime check.
 *
 * Why: unit tests exercise web-ifc's NODE build; the packaged app runs web-ifc's BROWSER
 * build inside a Chromium Worker, loaded over file://. This harness verifies that real
 * packaged path WITHOUT needing auth, the API, or WebGL — IFC parse + scene assembly are
 * CPU/JS; only rendering needs a GPU. It loads out/renderer/worker-test.html (generated by
 * gen.cjs) over file://, which drives the BUILT ifc.worker chunk against a fixture IFC and
 * logs a single WORKER_TEST_DONE line.
 *
 * Don't run directly — use run.sh (it wraps xvfb-run + electron and stages the fixture).
 * Exits 0 only on "WORKER_TEST_DONE OK"; non-zero on init/parse/worker error or timeout.
 */
const { app, BrowserWindow } = require('electron');
const path = require('node:path');

// __dirname = apps/desktop/scripts/ifc-worker-harness  →  build output at apps/desktop/out/renderer
const RENDERER_DIR = path.join(__dirname, '..', '..', 'out', 'renderer');

app.commandLine.appendSwitch('no-sandbox');

app.whenReady().then(() => {
  const win = new BrowserWindow({
    show: false,
    webPreferences: { nodeIntegration: false, contextIsolation: true },
  });
  let done = false;
  const finish = (code) => { if (!done) { done = true; setTimeout(() => app.exit(code), 150); } };

  win.webContents.on('console-message', (_e, _level, message) => {
    console.log('RENDERER> ' + message);
    if (message.includes('WORKER_TEST_DONE')) finish(message.includes(' OK ') ? 0 : 3);
  });
  win.webContents.on('render-process-gone', (_e, d) => {
    console.log('RENDER_GONE ' + JSON.stringify(d));
    finish(4);
  });

  const file = path.join(RENDERER_DIR, 'worker-test.html');
  console.log('LOADING ' + file);
  win.loadFile(file);

  setTimeout(() => { console.log('TIMEOUT (no WORKER_TEST_DONE in 30s)'); finish(5); }, 30000);
});
