#!/usr/bin/env bash
# run-desktop.sh — one command to launch the full NodeScope stack + the 3D desktop app.
#
# Automates SETUP.md end-to-end on a REAL-GPU machine (native Linux / macOS / WSLg).
# Since the Decision 11 cutover the backend is the self-hosted APPLIANCE compose
# (C# API + same-origin web through Caddy at :8080 — the API ships no CORS, so the
# old cross-origin dev-web flow is gone):
#   deploy compose (db → api, migrates on boot → caddy/web) → demo seed (org, devices,
#   FZK-Haus sample model) → Electron 3D viewer pointed at http://localhost:8080/api.
#
# The desktop viewer needs a real display + GPU and PKCE sign-in opens your system
# browser — so run this where you have a GUI, not in a headless container.
#
# Idempotent: the compose services and the seed are; re-run freely.
#
# Usage:
#   ./scripts/run-desktop.sh                # full bring-up, then open the desktop
#   ./scripts/run-desktop.sh --reset        # wipe the stack's volumes first (fresh DB)
#   ./scripts/run-desktop.sh --no-model     # skip the FZK-Haus sample-model upload
#   ./scripts/run-desktop.sh --desktop-only # backend already up elsewhere; just open the app
#   ./scripts/run-desktop.sh --backend-only # bring the appliance up, no GUI
#   ./scripts/run-desktop.sh --stop         # stop the appliance stack (volumes kept)
#
# Env overrides: SEED_EMAIL, SEED_PASSWORD (defaults owner@acme.test / devpassword123)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/deploy/.env.desktop-dev"
COMPOSE=(docker compose -f deploy/docker-compose.prod.yml -f deploy/docker-compose.build.yml -f deploy/docker-compose.demo.yml --env-file "$ENV_FILE")
ORIGIN="http://localhost:8080"

c(){ printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
log(){  c '1;36' "▶ $*"; }
warn(){ c '1;33' "! $*"; }
die(){  c '1;31' "✖ $*" >&2; exit 1; }

# ── args ─────────────────────────────────────────────────────────────────────
DO_BACKEND=1 DO_DESKTOP=1 RESET=0
export SEED_SAMPLE_MODEL="${SEED_SAMPLE_MODEL:-true}"
for a in "$@"; do case "$a" in
  --reset) RESET=1;;
  --no-model) export SEED_SAMPLE_MODEL=false;;
  --desktop-only) DO_BACKEND=0;;
  --backend-only) DO_DESKTOP=0;;
  --stop) [ -f "$ENV_FILE" ] || die "no $ENV_FILE — nothing this script started"; "${COMPOSE[@]}" down; exit 0;;
  -h|--help) grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
  *) die "unknown arg: $a (try --help)";;
esac; done

# ── backend: the appliance compose ───────────────────────────────────────────
if [ "$DO_BACKEND" = 1 ]; then
  command -v docker >/dev/null || die "docker not found (needed for the appliance; or pass --desktop-only)"

  # Local-dev env for the appliance: generated once, reused after (idempotent).
  if [ ! -f "$ENV_FILE" ]; then
    log "generating $ENV_FILE (localhost appliance secrets) ..."
    {
      echo "# Generated by scripts/run-desktop.sh for LOCAL DEV — safe to delete; git-ignored."
      echo "PUBLIC_ORIGIN=${ORIGIN}"
      echo "POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
      echo "BETTER_AUTH_SECRET=$(openssl rand -base64 48 | tr -d '\n')"
      echo "SECRET_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')"
      echo "SEED_PASSWORD=${SEED_PASSWORD:-devpassword123}"
    } >"$ENV_FILE"
  fi

  if [ "$RESET" = 1 ]; then log "resetting the stack (volumes wiped) ..."; "${COMPOSE[@]}" down -v; fi

  log "building + starting the appliance (db → api → web) — first build takes a while ..."
  "${COMPOSE[@]}" up -d --build --wait db api web

  log "seeding demo data (org, devices, building model${SEED_SAMPLE_MODEL:+, sample model=$SEED_SAMPLE_MODEL}) ..."
  "${COMPOSE[@]}" up demo-seed --no-log-prefix | grep -E "Seeded|skipping|Seed complete" || true

  curl -fsS "$ORIGIN/api/health" >/dev/null || die "API not healthy at $ORIGIN/api/health"
  log "appliance is up: $ORIGIN (web) · $ORIGIN/api (API)"
fi

# ── desktop (foreground GUI) ─────────────────────────────────────────────────
if [ "$DO_DESKTOP" = 1 ]; then
  command -v node >/dev/null || die "Node.js not found (need 20–22 for the Electron dev shell)"
  node_major=$(node -v | sed 's/^v\([0-9]*\).*/\1/')
  if [ "$node_major" -lt 20 ] || [ "$node_major" -gt 22 ]; then
    die "Node $node_major detected — this project needs Node 20–22. With nvm: 'nvm install 22 && nvm use 22'."
  fi
  [ -d node_modules ] || { log "installing dependencies (first run — a few minutes) ..."; npm install; }
  [ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ] || warn "no DISPLAY/WAYLAND_DISPLAY — the Electron window needs a display (WSLg/native X/Wayland)."
  if [ "$(id -u)" = 0 ]; then warn "running as root — if Electron exits with a sandbox error, run as a non-root user."; fi
  echo
  c '1;32' "── Server: ${ORIGIN}/api  ·  Sign in: ${SEED_EMAIL:-owner@acme.test} / ${SEED_PASSWORD:-devpassword123} ──"
  c '1;32' "   Verify in the 3D viewer (open Main Building):"
  c '0'    "     1) NO-FREEZE  — spinner keeps animating through the parse"
  c '0'    "     2) PICKING    — click an element → Inspector populates"
  c '0'    "     3) BCF        — Issues panel → a viewpoint restores camera + visibility"
  echo
  log "launching desktop (dev:desktop) — close the window or Ctrl-C when done"
  npm run dev:desktop
else
  log "backend is up: $ORIGIN — stop it later with:  $0 --stop"
fi
