#!/usr/bin/env bash
# One command to launch the NodeScope appliance and native desktop client.
#
# The appliance compose provides PostgreSQL, the ASP.NET Core API, and the
# same-origin Caddy gateway at http://localhost:8080. The foreground
# application is the Avalonia client in src/NodeScope.Desktop.
#
# The desktop viewer needs a real display + GPU, so run this where you have a GUI.
# Sign-in is native - email and password go straight into the app.
#
# Idempotent: the compose services and the seed are; re-run freely.
#
# Usage:
#   ./scripts/run-desktop.sh                # full bring-up, then open the desktop
#   ./scripts/run-desktop.sh --reset        # wipe the stack's volumes first (fresh DB)
#   ./scripts/run-desktop.sh --no-model     # skip the FZK-Haus sample-model upload
#   ./scripts/run-desktop.sh --desktop-only # backend already up elsewhere; just open the app
#   ./scripts/run-desktop.sh --backend-only # bring the appliance up, no GUI
#   ./scripts/run-desktop.sh --stop         # stop the appliance stack (volumes kept)
#
# Env overrides: SEED_EMAIL, SEED_PASSWORD (defaults owner@acme.test / devpassword123)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/deploy/.env.desktop-dev"
COMPOSE=(docker compose -f deploy/docker-compose.prod.yml -f deploy/docker-compose.build.yml -f deploy/docker-compose.demo.yml --env-file "$ENV_FILE")
ORIGIN="http://localhost:8080"

c(){ printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
log(){  c '1;36' "▶ $*"; }
warn(){ c '1;33' "! $*"; }
die(){  c '1;31' "✖ $*" >&2; exit 1; }

# Arguments
DO_BACKEND=1 DO_DESKTOP=1 RESET=0
export SEED_SAMPLE_MODEL="${SEED_SAMPLE_MODEL:-true}"
for a in "$@"; do case "$a" in
  --reset) RESET=1;;
  --no-model) export SEED_SAMPLE_MODEL=false;;
  --desktop-only) DO_BACKEND=0;;
  --backend-only) DO_DESKTOP=0;;
  --stop) [ -f "$ENV_FILE" ] || die "no $ENV_FILE - nothing this script started"; "${COMPOSE[@]}" down; exit 0;;
  -h|--help) grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
  *) die "unknown arg: $a (try --help)";;
esac; done

# Appliance
if [ "$DO_BACKEND" = 1 ]; then
  command -v docker >/dev/null || die "docker not found (needed for the appliance; or pass --desktop-only)"

  # Local-dev env for the appliance: generated once, reused after (idempotent).
  if [ ! -f "$ENV_FILE" ]; then
    log "generating $ENV_FILE (localhost appliance secrets) ..."
    {
      echo "# Generated by scripts/run-desktop.sh for local development. Safe to delete; git-ignored."
      echo "PUBLIC_ORIGIN=${ORIGIN}"
      echo "POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
      echo "SECRET_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')"
      echo "BOOTSTRAP_TOKEN=desktop-dev-bootstrap"
      echo "SEED_PASSWORD=${SEED_PASSWORD:-devpassword123}"
    } >"$ENV_FILE"
  fi

  if [ "$RESET" = 1 ]; then log "resetting the stack (volumes wiped) ..."; "${COMPOSE[@]}" down -v; fi

  log "building + starting the appliance (db -> api -> web); the first build takes a while ..."
  "${COMPOSE[@]}" up -d --build --wait db api web

  log "seeding demo data (org, devices, building model${SEED_SAMPLE_MODEL:+, sample model=$SEED_SAMPLE_MODEL}) ..."
  "${COMPOSE[@]}" run --rm demo-seed

  curl -fsS "$ORIGIN/api/health" >/dev/null || die "API not healthy at $ORIGIN/api/health"
  log "appliance is up: $ORIGIN (enter this origin in the desktop client)"
fi

# Native desktop client
if [ "$DO_DESKTOP" = 1 ]; then
  if command -v dotnet >/dev/null 2>&1; then
    DOTNET_CMD=dotnet
  elif [ -x "$HOME/.dotnet/dotnet" ]; then
    DOTNET_CMD="$HOME/.dotnet/dotnet"
  else
    die ".NET 10 SDK not found"
  fi
  [ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ] || warn "no DISPLAY/WAYLAND_DISPLAY - the Avalonia window needs a display"
  echo
  c '1;32' "Server: ${ORIGIN}"
  c '1;32' "Sign in: ${SEED_EMAIL:-owner@acme.test} / ${SEED_PASSWORD:-devpassword123}"
  c '0' "Enter the server origin without /api when the client opens."
  echo
  log "launching the native desktop client; close the window or press Ctrl-C when done"
  "$DOTNET_CMD" run --project src/NodeScope.Desktop
else
  log "backend is up: $ORIGIN - stop it later with: $0 --stop"
fi
