<#
.SYNOPSIS
  One command to launch the full NodeScope stack + the 3D desktop app on Windows.

.DESCRIPTION
  PowerShell twin of scripts/run-desktop.sh (see it for the full story). Since the
  Decision 11 cutover the backend is the self-hosted APPLIANCE compose (C# API +
  same-origin web through Caddy at :8080); the Electron viewer points at
  http://localhost:8080/api and PKCE sign-in opens your default browser.

  Run it from inside the repo. Needs Node 20-22, Docker Desktop (running), and a real
  display + GPU (native Windows). If PowerShell blocks the script, either run
  'Set-ExecutionPolicy -Scope CurrentUser RemoteSigned' once, or launch it with
  'powershell -ExecutionPolicy Bypass -File .\scripts\run-desktop.ps1'.

.PARAMETER Reset        Wipe the stack's volumes first (fresh DB + blobstore).
.PARAMETER NoModel      Skip the FZK-Haus sample-model upload.
.PARAMETER DesktopOnly  Backend already up elsewhere; just open the desktop.
.PARAMETER BackendOnly  Bring the appliance up, no GUI.
.PARAMETER Stop         Stop the appliance stack (volumes kept).
#>
[CmdletBinding()]
param(
    [switch]$Reset,
    [switch]$NoModel,
    [switch]$DesktopOnly,
    [switch]$BackendOnly,
    [switch]$Stop
)
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$EnvFile = Join-Path $Root 'deploy/.env.desktop-dev'
$Origin = 'http://localhost:8080'
$ComposeArgs = @(
    'compose',
    '-f', 'deploy/docker-compose.prod.yml',
    '-f', 'deploy/docker-compose.build.yml',
    '-f', 'deploy/docker-compose.demo.yml',
    '--env-file', $EnvFile
)

function Log($msg)  { Write-Host ("> " + $msg) -ForegroundColor Cyan }
function Warn($msg) { Write-Host ("! " + $msg) -ForegroundColor Yellow }
function Fail($msg) { Write-Host ("x " + $msg) -ForegroundColor Red; exit 1 }

function New-Base64Secret([int]$bytes) {
    $buffer = [byte[]]::new($bytes)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
    [Convert]::ToBase64String($buffer)
}

if ($Stop) {
    if (-not (Test-Path $EnvFile)) { Fail "no $EnvFile - nothing this script started" }
    docker @ComposeArgs down
    exit $LASTEXITCODE
}

$env:SEED_SAMPLE_MODEL = if ($NoModel) { 'false' } else { 'true' }

if (-not $DesktopOnly) {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail 'docker not found (needed for the appliance; or pass -DesktopOnly)' }

    if (-not (Test-Path $EnvFile)) {
        Log "generating $EnvFile (localhost appliance secrets) ..."
        $seedPassword = if ($env:SEED_PASSWORD) { $env:SEED_PASSWORD } else { 'devpassword123' }
        @(
            '# Generated by scripts/run-desktop.ps1 for LOCAL DEV - safe to delete; git-ignored.'
            "PUBLIC_ORIGIN=$Origin"
            "POSTGRES_PASSWORD=$(New-Base64Secret 24)"
            "BETTER_AUTH_SECRET=$(New-Base64Secret 48)"
            "SECRET_ENCRYPTION_KEY=$(New-Base64Secret 32)"
            "SEED_PASSWORD=$seedPassword"
        ) | Set-Content -Path $EnvFile -Encoding ascii
    }

    if ($Reset) {
        Log 'resetting the stack (volumes wiped) ...'
        docker @ComposeArgs down -v
    }

    Log 'building + starting the appliance (db -> api -> web) - first build takes a while ...'
    docker @ComposeArgs up -d --build --wait db api web
    if ($LASTEXITCODE -ne 0) { Fail 'compose up failed' }

    Log 'seeding demo data (org, devices, building model, sample model) ...'
    docker @ComposeArgs up demo-seed --no-log-prefix
    if ($LASTEXITCODE -ne 0) { Fail 'demo seed failed' }

    try { Invoke-RestMethod "$Origin/api/health" | Out-Null }
    catch { Fail "API not healthy at $Origin/api/health" }
    Log "appliance is up: $Origin (web) - $Origin/api (API)"
}

if (-not $BackendOnly) {
    if (-not (Get-Command node -ErrorAction SilentlyContinue)) { Fail 'Node.js not found (need 20-22 for the Electron dev shell)' }
    $nodeMajor = [int]((node -v) -replace '^v(\d+).*', '$1')
    if ($nodeMajor -lt 20 -or $nodeMajor -gt 22) { Fail "Node $nodeMajor detected - this project needs Node 20-22" }
    if (-not (Test-Path (Join-Path $Root 'node_modules'))) {
        Log 'installing dependencies (first run - a few minutes) ...'
        npm install
        if ($LASTEXITCODE -ne 0) { Fail 'npm install failed' }
    }

    $seedEmail = if ($env:SEED_EMAIL) { $env:SEED_EMAIL } else { 'owner@acme.test' }
    $seedPassword = if ($env:SEED_PASSWORD) { $env:SEED_PASSWORD } else { 'devpassword123' }
    Write-Host ''
    Write-Host "-- Server: $Origin/api  -  Sign in: $seedEmail / $seedPassword --" -ForegroundColor Green
    Write-Host '   Verify in the 3D viewer (open Main Building): no-freeze spinner, element picking, BCF viewpoints.' -ForegroundColor Green
    Write-Host ''
    Log 'launching desktop (dev:desktop) - close the window or Ctrl-C when done'
    npm run dev:desktop
}
else {
    Log "backend is up: $Origin - stop it later with:  .\scripts\run-desktop.ps1 -Stop"
}
