<#
.SYNOPSIS
  Launch the NodeScope appliance and native desktop client on Windows.

.DESCRIPTION
  PowerShell twin of scripts/run-desktop.sh. The backend is the self-hosted
  appliance compose (ASP.NET Core API plus same-origin web through Caddy at
  http://localhost:8080). The foreground app is the Avalonia client.

  Run it from inside the repo. Needs the .NET 10 SDK, Docker Desktop, and a real
  display. If PowerShell blocks the script, either run
  'Set-ExecutionPolicy -Scope CurrentUser RemoteSigned' once, or launch it with
  'powershell -ExecutionPolicy Bypass -File .\scripts\run-desktop.ps1'.

.PARAMETER Reset        Wipe the stack's volumes first (fresh DB + blobstore).
.PARAMETER NoModel      Skip the FZK-Haus sample-model upload.
.PARAMETER DesktopOnly  Backend already up elsewhere; just open the desktop.
.PARAMETER BackendOnly  Bring the appliance up, no GUI.
.PARAMETER Stop         Stop the appliance stack (volumes kept).
#>
[CmdletBinding()]
param(
    [switch]$Reset,
    [switch]$NoModel,
    [switch]$DesktopOnly,
    [switch]$BackendOnly,
    [switch]$Stop
)
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$EnvFile = Join-Path $Root 'deploy/.env.desktop-dev'
$Origin = 'http://localhost:8080'
$ComposeArgs = @(
    'compose',
    '-f', 'deploy/docker-compose.prod.yml',
    '-f', 'deploy/docker-compose.build.yml',
    '-f', 'deploy/docker-compose.demo.yml',
    '--env-file', $EnvFile
)

function Log($msg)  { Write-Host ("> " + $msg) -ForegroundColor Cyan }
function Warn($msg) { Write-Host ("! " + $msg) -ForegroundColor Yellow }
function Fail($msg) { Write-Host ("x " + $msg) -ForegroundColor Red; exit 1 }

function New-Base64Secret([int]$bytes) {
    $buffer = [byte[]]::new($bytes)
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
        [Convert]::ToBase64String($buffer)
    }
    finally {
        $generator.Dispose()
    }
}

function New-HexSecret([int]$bytes) {
    $buffer = [byte[]]::new($bytes)
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
        [BitConverter]::ToString($buffer).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $generator.Dispose()
    }
}

if ($Stop) {
    if (-not (Test-Path $EnvFile)) { Fail "no $EnvFile - nothing this script started" }
    docker @ComposeArgs down
    exit $LASTEXITCODE
}

$env:SEED_SAMPLE_MODEL = if ($NoModel) { 'false' } else { 'true' }

if (-not $DesktopOnly) {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail 'docker not found (needed for the appliance; or pass -DesktopOnly)' }

    if (-not (Test-Path $EnvFile)) {
        if (-not $Reset) {
            docker volume inspect nodescope_pgdata *> $null
            if ($LASTEXITCODE -eq 0) {
                Fail "$EnvFile is missing while the NodeScope database volume exists; restore the file or rerun with -Reset to replace the local appliance"
            }
        }
        Log "generating $EnvFile (localhost appliance secrets) ..."
        $seedPassword = if ($env:SEED_PASSWORD) { $env:SEED_PASSWORD } else { 'devpassword123' }
        @(
            '# Generated by scripts/run-desktop.ps1 for local development. Keep with the Docker volumes; git-ignored.'
            "PUBLIC_ORIGIN=$Origin"
            "POSTGRES_PASSWORD=$(New-HexSecret 32)"
            "SECRET_ENCRYPTION_KEY=$(New-Base64Secret 32)"
            'BOOTSTRAP_TOKEN=desktop-dev-bootstrap'
            "SEED_PASSWORD=$seedPassword"
        ) | Set-Content -Path $EnvFile -Encoding ascii
    }

    if ($Reset) {
        Log 'resetting the stack (volumes wiped) ...'
        docker @ComposeArgs down -v
    }

    Log 'building + starting the appliance (db -> api -> web); the first build takes a while ...'
    docker @ComposeArgs up -d --build --wait db api web
    if ($LASTEXITCODE -ne 0) { Fail 'compose up failed' }

    Log 'seeding demo data (org, devices, building model, sample model) ...'
    docker @ComposeArgs run --rm demo-seed
    if ($LASTEXITCODE -ne 0) { Fail 'demo seed failed' }

    try { Invoke-RestMethod "$Origin/api/health" | Out-Null }
    catch { Fail "API not healthy at $Origin/api/health" }
    Log "appliance is up: $Origin (enter this origin in the desktop client)"
}

if (-not $BackendOnly) {
    if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) { Fail '.NET 10 SDK not found' }

    $seedEmail = if ($env:SEED_EMAIL) { $env:SEED_EMAIL } else { 'owner@acme.test' }
    $seedPassword = if ($env:SEED_PASSWORD) { $env:SEED_PASSWORD } else { 'devpassword123' }
    Write-Host ''
    Write-Host "Server: $Origin" -ForegroundColor Green
    Write-Host "Sign in: $seedEmail / $seedPassword" -ForegroundColor Green
    Write-Host 'Enter the server origin without /api when the client opens.' -ForegroundColor Green
    Write-Host ''
    Log 'launching the native desktop client; close the window or press Ctrl-C when done'
    dotnet run --project src/NodeScope.Desktop
    if ($LASTEXITCODE -ne 0) { Fail 'desktop client exited with an error' }
}
else {
    Log "backend is up: $Origin - stop it later with:  .\scripts\run-desktop.ps1 -Stop"
}
